config/routes.rb
Rails.application.routes.draw do
  use_doorkeeper
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }

  root to: "pages#index"

  resources "games", only: [:new, :show, :create]
  post "/games/:id/turn", to: "games#turn"
  post "/games/:id/stacks", to: "games#new_stack"

  get "/friends", to: "friends#list"

  namespace :admin do
    get "/test", to: "test#show"
  end

  namespace :api do
    namespace :v1 do
      post "/auth/create", to: "auth#create"

      get "/dashboard", to: "dashboard#index"

      resources "games", only: [:new, :show, :create]
      post "/games/:id/turn", to: "games#turn"
      post "/games/:id/stacks", to: "games#new_stack"

      post "/devices/register", to: "devices#register"

      get "/friends/list", to: "friends#list"
    end
  end
end

app/views/pages/index.html.erb
<% # view is an instance of Pages::IndexView %>

<div class="container">
  <div class="row">
    <div class="col-xs-12">

      <div class="row">
        <div id="root"></div>
      </div>

      <% if current_user %>
        <div class="clearfix">
          <a href=<%= new_game_path %> class="btn btn-primary float-right" style="margin-bottom:10px;">New Game</a>
          <h4 class="float-left">Games</h4>
        </div>
        <% if view.active_game_previews.any? %>
          <div class="friends-list">
            <ul class="list-unstyled">
              <% view.active_game_previews.each do |game_preview| %>
                <li>
                  <img src=<%= game_preview.opponent.image %> width="30" height="30" />
                  <%= game_preview.opponent.name %>
                  <% viewers_turn = game_preview.viewers_turn? %>
                  <% if viewers_turn %>
                    <small>( your turn )</small>
                  <% else %>
                    <small>( their turn )</small>
                  <% end %>
                  <a href="<%= game_path(game_preview.game.id) %>" class="float-right">play</a>
                </li>
              <% end %>
            </ul>
          </div>
        <% end %>

        <hr>

        <h4>Invites:</h4>

        <% if view.invites.any? %>
          <div class="friends-list">
            <ul class="list-unstyled">
              <% view.invites.each do |invite| %>
                <li>
                  <img src=<%= invite.user.image %> width="30" height="30" />
                  <%= invite.user.name %>
                  <a href="<%= game_path(invite.game_id) %>" class="btn btn-success float-right">Join</a>
                </li>
              <% end %>
            </ul>
          </div>
        <% end %>

      <% else %>
        <%= link_to "Sign in with Facebook", user_facebook_omniauth_authorize_path, class: "btn btn-primary" %>
        <% if Rails.env.development? %>
          or
          <a href="https://developers.facebook.com/checkpoint/test-user-login/101441640615588/" target="_blank">Log in as test user</a>
        <% end %>
      <% end %>
    </div>
  </div>
</div>